name: Build and Publish Docker Image
on: 
    release:
        types: [published, edited]    

jobs:
    push-to-dockerhub-and-ghcr:
        runs-on: ubuntu-latest
        permissions:
          packages: write
          contents: read
        steps:
            - uses: actions/checkout@v5
            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Extract metadata
              id: metadata
              uses: docker/metadata-action@v5
              with: 
                images: |
                 gauri01234/docker-images-ga
                 ghcr.io/${{ github.repository }}
                tags: |
                  type=semver,pattern={{version}}
                  type=semver,pattern={{major}}.{{minor}}
            - name: Build & Publish Docker Image
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ steps.metadata.outputs.tags }}
                labels: ${{ steps.metadata.outputs.labels}}