name: Caching and Artifacts
on: [workflow_dispatch]

jobs:
    use-axios:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Cache node modules
              id: cache-dependencies
              uses: actions/cache@v3
              with:
                path: ~/.npm
                # key: "npm-cache"
                key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}  #linux-npm-cache7383493
                restore-keys: |
                  ${{ runner.os }}-npm-cache-
                  ${{ runner.os }}-
            - name: Display cache Output
              run: echo '${{ toJson(steps.cache-dependencies.outputs) }}'
            - name: Install dependencies
              run: npm install
            - name: Run Tests
              run: npm test
            - name: Upload Code Coverage Report         # Name of the artifact to upload.
              uses: actions/upload-artifact@v3          # A file, directory or wildcard pattern that describes what to upload
              if: always()         
              #we need to always run this test even if test has failed, so we can add always, even if test fail we still upload our generated coverage reports
              with: 
                name: code-coverage
                path: coverage
                retention-days: 10
            - name: Use Axios
              uses: actions/github-script@v6
              with:
                script: |
                  const axios = require('axios');
                  const res = await axios('https://icanhazdadjoke.com/', { headers: { Accept: 'text/plain' } })
                  console.log(res.data)

#npm i -D jest installs Jest as a dev-only tool for writing and running tests, without bloating your production dependencies.