name: Checkout
on: [push]

jobs: 
    checkout-and-display-files:
        runs-on: ubuntu-latest
        steps:
            - name: List files Before
              run: ls -a
            - name: Checkout
              run: |
                git init      #In our virtual machone or runner where our job is running we can initializa a new git repository in our working directory
                git remote add origin "https://$GITHUB_ACTOR":${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git             #As a remote we can add our repository
                git fetch origin 
                git checkout main
            - name: List files after
              run: ls -a

                

