name: Matrix
on: [push]

#------- ORIGINAL --------#
# {os: ubuntu-latest, node-version: 14}
# {os: ubuntu-latest, node-version: 15}
# {os: ubuntu-latest, node-version: 16}
# {os: windows-latest, node-version: 14}
# {os: windows-latest, node-version: 15}
# {os: windows-latest, node-version: 16}

#------- After changes --------#
# X {os: ubuntu-latest, node-version: 14, is-ubuntu: true, experimental: false}  #excluded
# {os: ubuntu-latest, node-version: 15, is-ubuntu: true, experimental: false}
# {os: ubuntu-latest, node-version: 16, is-ubuntu: true, experimental: true}
# {os: windows-latest, node-version: 14, experimental: false}
# {os: windows-latest, node-version: 15, experimental: false}
# {os: windows-latest, node-version: 16, experimental: false}
# {os: macos-latest, node-version: 15}      #new combination
# {os: ubuntu-latest, node-version: 16}      #new combination



jobs: 
    node-matrix:
        continue-on-error: true
        strategy:
            matrix:
              os: [ubuntu-latest, windows-latest]
              node-version: [14,15,16]
              include:
                - os: ubuntu-latest
                  is-ubuntu: true
                - os: macos-latest      #original values can't be overwritten
                  node-version: 16
                - experimental: false   #this value can't be added on the new combination as it will be added only on the original combinations
                - os: ubuntu-latest     #here added matrix value like experimental : true is overwritten but original ones will not be overwritten
                  node-version: 16
                  experimental : true
                - os: ubuntu-latest
                  node-version: 17
              exclude: 
                - os: ubuntu-latest
                  node-version: 14   
            #max-parallel: 3
            fail-fast: false
        runs-on: ${{ matrix.os }}
        steps:
            - run: node -v
            - uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - run: node -v


