name: Pull Request Comment
on:
    pull_request_target:
        types: [opened]
jobs:
    pr-comment:
        runs-on: ubuntu-latest
        permissions: 
            pull_requests: write 
            #to create a comment on PR and all other scopes will be none
            #contents: read   #default permission
            # we can directly assign permissions: read-all or write-all or {} which means no permissions and it will be applied to all scopes
        steps:
            - name: Comment on New PRs
              uses: actions/github-script@v6   #this github action uses the GITHUB_TOKEN secret for authentication by default
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                    github.rest.issues.createComment({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      issue_number: context.issue.number,     #PR number
                      body: 'Thanks for contributing!',
                    });