name: Calling reusable Workflows
on: 
    workflow_dispatch:
        inputs:
            name: 
                description: "Input description"
                type: string
                default: "Ali"
                required: false

jobs:
    calling-a-reusable-wf:          #from different repo in same org
        uses: GauriAgarwal0404/Github_Actions_Notes/.github/workflows/reusable.yaml@main
        with:
            name: ${{ inputs.name }}
        secrets:
            access-token: ${{ secrets.ACCESS_TOKEN }}
    calling-a-reusable-workflow-in-the-same-repo:
        # permissions:
        #     issues: read
        uses: ./.github/workflows/reusable-workflow.yaml
        secrets: inherit
    using-reusable-workflow-output:
        runs-on: ubuntu-latest
        needs: calling-a-reusable-workflow-in-the-same-repo
        steps:
            - run: echo ${{ needs.calling-a-reusable-workflow-in-the-same-repo.outputs.date }}

    



