name: Workflow Run
on:
    workflow_run:
        workflows: [Repository Events]              #as long as reposiotry events ran on main branch
        types: [completed]
        branches:
            - main
jobs:
    echo-string:
        runs-on: ubuntu-latest
        steps: 
            - run: echo "I was triggered bacuse 'Repository Events' was completed"


# on:
#   workflow_run:
#     workflows: [Build]
#     types: [requested]
#     branches: [canary]
